version: '3'

services:
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - enviroment.env
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
  web:
    build: ./todolist_server
    volumes:
      - ./todolist_server:/todolist_server
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - enviroment.env
    command: python3 manage.py runserver 0.0.0.0:8000