version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: ./todolist_server
    volumes:
      - ./todolist_server:/todolist_server
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000