# Generated by Django 3.2.9 on 2021-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='exponent',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='m',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
